language: scala
scala:
  - 2.10.5
  - 2.11.7
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
script: 
  - travis_retry "./travis.sh"
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
